# Generated by Django 4.1.7 on 2023-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='MyApp.subcategory'),
        ),
    ]
